version: 2.1
workflows:
    lint_and_test:
        jobs:
            - build
            - lint
            - circuits-test:
                  requires:
                      - build
            - contracts-test:
                  requires:
                      - build

# Just for reusing below
step_defs:
    - run: &node_version
          name: Set Node version
          command: |
              nvm install v18
              nvm alias default v18
              echo "nvm use default" >> $BASH_ENV
    - run: &check_version
          name: Check Node version
          command: node -v | grep v18
    - run: &install_circom
          name: Install Circom
          command: |
              curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
              source "$HOME/.cargo/env"
              cd /tmp
              git clone https://github.com/iden3/circom.git
              cd circom
              cargo build --release
              cargo install --path circom

jobs:
    build:
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - attach_workspace:
                  at: ~/project
            - run: *node_version
            - run: *check_version
            - run: *install_circom
            - run:
                  name: Install Packages
                  command: yarn
            - run:
                  name: Build
                  command: |
                      yarn build
            - persist_to_workspace:
                  root: ~/project
                  paths:
                      - node_modules
                      - packages/circuits/zksnarkBuild
                      - packages/circuits/dist
                      - packages/contracts/artifacts
                      - packages/contracts/cache
                      - packages/contracts/typechain-types
                      - packages/contracts/contracts
    lint:
        machine:
            image: ubuntu-2204:2022.04.1
        resource_class: medium
        steps:
            - checkout
            - run: *node_version
            - run: *check_version
            - run:
                  name: Install
                  command: yarn
            - run:
                  name: Lint
                  command: yarn lint --check
    circuits-test:
        resource_class: medium
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - attach_workspace:
                  at: ~/project
            - run: *node_version
            - run: *check_version
            - run:
                  name: Test
                  command: yarn circuits test
    contracts-test:
        resource_class: large
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - attach_workspace:
                  at: ~/project
            - run: *node_version
            - run: *check_version
            - run:
                  name: Test
                  command: yarn contracts test
