name: Environment Check CI

on:
    push:
        branches:
            - main

jobs:
    create-unirep-app:
        strategy:
            matrix:
                node-version: [18.x, 20.x]
                os: [macos-latest, ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm install -g create-unirep-app
            - run: (echo -e "example"; sleep 1; echo -e '\n'; sleep 1; echo -e '\n')| npx create-unirep-app
            - run: cd example && yarn build

    create-unirep-app-windows:
        runs-on: windows-latest
        strategy:
            matrix:
                node-version: [18.x, 20.x]
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm install -g create-unirep-app
            - run: |
                  $command = '"example"; Start-Sleep -Seconds 3; "`r`n"; Start-Sleep -Seconds 3; "`r`n";'  
                  Invoke-Expression -Command $command | npx create-unirep-app
            - run: cd example && yarn build
